title: Jun Blog
subTitle:개발 블로그 since 2020.12
iconURL: assets/default-icon.png
theme: minima

# for a clean URL
permalink: :slug

url: "https://junblog.github.io"
social:
  github: junblog

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
